### ISSUE TITLE
make it compatible for 5.4 that is required spatie/laravel-backup 4.2 

### ISSUE THREAD

**Issue by msonowal** [Laravel-Backpack/BackupManager#21] opened 2017-02-01 14:31 UTC
Make it compatible for 5.4 that is required spatie/laravel-backup 4.2 as per dev dependecy

**Comment by alexstudle** [comment] 2017-04-10 09:03
Hello,

just wanted to ask if you have any update/news for this ? 
I'm having problems with the BackupManager in Laravel 5.4 and I think it could be related to this incompatibility problem

Thank you, Alex

**Comment by tabacitu** [comment] 2017-04-10 17:02
Hi @alexstudle ,

What problems are you having? I'm asking because I found no with it installed on L5.4.

Cheers!

**Comment by alexstudle** [comment] 2017-04-10 17:49
Hi @tabacitu ,

thanks for your quick answer !!

My problem is that I can't backup, I'm getting an error TimeOut in "spatie/laravel-backup/src/Tasks/Backup/Zip.php"

I'm using php 7.0 and laravel 5.4.
After reading the spatie documentation (https://docs.spatie.be/laravel-backup/v4/introduction) I found out there's a version 4.* of laravel-backup. It seems like this version also has multiple fixes (like the one mentioned here: https://github.com/Laravel-Backpack/BackupManager/issues/24, I have this same problem)

I tried to upgrade spatie/laravel-backup but it remains impossible because it is not compatible with the BackupManager.

So maybe there's another solution or the problem is somewhere else ?

**Comment by lloy0076** [comment] 2017-07-08 20:43
Is this still an issue?

The devil in me is more inclined to say that there really IS  a timeout as opposed to there is a bug? Or that the bug is that there isn't a way to increase the timeout value in the underlying version of the backup tool...

**Comment by DaveThe** [comment] 2017-08-29 14:25
i have notice another issue in laravel 5.4 and php 7.
The package used to send notifications via slack is deprecated and not compatible with L5.4 and now i can't use it.

It's possibile to upgrade the spatie package or it's better to fork this package?
Thanks

**Comment by lloy0076** [comment] 2017-08-29 19:31
https://github.com/Laravel-Backpack/PermissionManager/pull/112 is a pull request that I'll look at shortly to update the permission manager.

**Comment by christiantigre** [comment] 2017-09-02 03:09
helpe!!
laravel 5.4
php 7.1
spatie 3.0.0 and 4.2

php artisan backup:run --only-db
Starting backup...
Dumping database pcsolutions...
Backup failed because The dump process failed with exitcode 1 : General error :
"mysqldump" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
.
Backup completed!

**Comment by DaveThe** [comment] 2017-09-04 08:15
Hi @christiantigre 
you should install mysqldump in your server but if you have host your site in a shared hosting you can't do it.

**Comment by uibar** [comment] 2017-09-05 22:32
Can't this also be closed by PR #41?

**Comment by DaveThe** [comment] 2017-09-06 21:26
No, sorry but after the upgrade to 1.2 i receive error on notification.
First of all there is no more this class "Spatie\Backup\Notifications\Notifier::class".
In config file of Spatie package there is this class instead "\Spatie\Backup\Notifications\Notifiable::class"

I tried to change it but now i receive this kind of error:

`Copying zip failed because: There is no notification class that can handle event `Spatie\Backup\Events\BackupWasSuccessful`..
Backup failed because There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFailed`..
#0 /var/www/mapor/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(57): Spatie\Backup\Exceptions\NotificationCouldNotBeSent::noNotifcationClassForEvent(Object(Spatie\Backup\Events\BackupHasFailed))
#1 /var/www/mapor/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(31): Spatie\Backup\Notifications\EventHandler->determineNotification(Object(Spatie\Backup\Events\BackupHasFailed))
#2 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(348): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}(Object(Spatie\Backup\Events\BackupHasFailed))
#3 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(199): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Spatie\\Backup\\E...', Array)
#4 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(446): Illuminate\Events\Dispatcher->dispatch('Spatie\\Backup\\E...')
#5 /var/www/mapor/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(255): event(Object(Spatie\Backup\Events\BackupHasFailed))
#6 /var/www/mapor/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(247): Spatie\Backup\Tasks\Backup\BackupJob->sendNotification(Object(Spatie\Backup\Events\BackupHasFailed))
#7 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Support/Collection.php(287): Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 0)
#8 /var/www/mapor/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(249): Illuminate\Support\Collection->each(Object(Closure))
#9 /var/www/mapor/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(137): Spatie\Backup\Tasks\Backup\BackupJob->copyToBackupDestinations('/var/www/mapor/...')
#10 /var/www/mapor/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(49): Spatie\Backup\Tasks\Backup\BackupJob->run()
#11 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#12 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#17 /var/www/mapor/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#18 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 /var/www/mapor/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(22): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/mapor/vendor/symfony/console/Application.php(888): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/mapor/vendor/symfony/console/Application.php(224): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/mapor/vendor/symfony/console/Application.php(125): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/mapor/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/mapor/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}
Backup failed because: There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFailed`..


  [Spatie\Backup\Exceptions\NotificationCouldNotBeSent]
  There is no notification class that can handle event `Spatie\Backup\Events\BackupHasFailed`.

`
It's me or something went wrong with the update?

Thanks

**Comment by DaveThe** [comment] 2017-09-06 22:08
Yes, i can confirm that the issue is the config file.

There is no more a "log" notification and it's no more necessary the additional package "maknz/slack"

If you change the notification block with this code everything go like a charm:
`
    'notifications' => [

        'notifications' => [
            \Spatie\Backup\Notifications\Notifications\BackupHasFailed::class         => ['mail'],
            \Spatie\Backup\Notifications\Notifications\UnhealthyBackupWasFound::class => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupHasFailed::class        => ['mail'],
            \Spatie\Backup\Notifications\Notifications\BackupWasSuccessful::class     => ['mail'],
            \Spatie\Backup\Notifications\Notifications\HealthyBackupWasFound::class   => ['mail'],
            \Spatie\Backup\Notifications\Notifications\CleanupWasSuccessful::class    => ['mail'],
        ],

        /*
         * Here you can specify the notifiable to which the notifications should be sent. The default
         * notifiable will use the variables specified in this config file.
         */
        'notifiable' => \Spatie\Backup\Notifications\Notifiable::class,

        'mail' => [
            'to' => 'your@email.com',
        ],

        'slack' => [
            'webhook_url' => '',
        ],
    ],`

**Comment by tabacitu** [comment] 2017-12-02 09:56
Fixed by Cristian's PR, so I'll close this. 1.3.x should fix all this - please reopen the issue if it doesn't for you (on L5.4).

Cheers!

**Closed** 2017-12-02 09:56 UTC
Labels: urgent
